import 'package:fashion_store/models/posts_response_model.dart' ;
import 'package:fashion_store/models/stories_response_model.dart' hide Owner;

final List<PostModel> postsFakeData = [
  PostModel(
    id: "post_1",
    text: "New summer collection just dropped ☀️👗",
    mediaUrl: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
    thumbnailUrl: null,
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    updatedAt: DateTime.now(),
    hasReacted: "like",
    isFollowed: true,
    reactions: Reactions(
      like: 120,
      love: 45,
      fire: 33,
    ),
    store: Store(
      id: "store_1",
      name: "Velvet Vogue",
      location: "Milan, Italy",
      latitude: "45.4642",
      longitude: "9.1900",
      logoUrl: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd53",
      mainImage: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
      description: "Luxury fashion boutique featuring modern European styles.",
      workingHours: "10:00 - 21:00",
      type: "Fashion",
      averageRating: 5,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      owner: Owner(
        id: "owner_1",
        firstName: "Sophia",
        lastName: "Rossi",
      ),
    ),
  ),
  PostModel(
    id: "post_2",
    text: "Minimalist streetwear for everyday style 🖤",
    mediaUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d",
    createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    updatedAt: DateTime.now(),
    hasReacted: null,
    isFollowed: true,
    reactions: Reactions(
      like: 98,
      love: 22,
      fire: 17,
    ),
    store: Store(
      id: "store_2",
      name: "Urban Thread",
      location: "London, UK",
      latitude: "51.5072",
      longitude: "-0.1276",
      logoUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8",
      mainImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d",
      description: "Premium streetwear and casual fashion.",
      workingHours: "09:00 - 22:00",
      type: "Streetwear",
      averageRating: 4,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      owner: Owner(
        id: "owner_2",
        firstName: "Oliver",
        lastName: "Smith",
      ),
    ),
  ),
  PostModel(
    id: "post_3",
    text: "Autumn essentials are here 🍂🧥",
    mediaUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    updatedAt: DateTime.now(),
    hasReacted: "fire",
    isFollowed: false,
    reactions: Reactions(
      like: 210,
      love: 88,
      fire: 120,
    ),
    store: Store(
      id: "store_3",
      name: "Nordic Style",
      location: "Stockholm, Sweden",
      latitude: "59.3293",
      longitude: "18.0686",
      logoUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b",
      mainImage: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
      description: "Clean Scandinavian fashion aesthetics.",
      workingHours: "10:00 - 20:00",
      type: "Minimal Fashion",
      averageRating: 5,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      owner: Owner(
        id: "owner_3",
        firstName: "Emma",
        lastName: "Lindberg",
      ),
    ),
  ),
];

final List<OwnerStory> storiesFakeData = [
  OwnerStory(
    store: Store(
      id: "store_1",
      name: "Velvet Vogue",
      location: "Milan, Italy",
      logoUrl: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd53",
      mainImage: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
      averageRating: 4,
      owner: Owner(
        id: "owner_1",
        firstName: "Sophia",
        lastName: "Rossi",
      ),
    ),
    stories: [
      Story(
        id: "story_1",
        mediaUrl: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
        text: "Summer dresses are back!",
        createdAt: DateTime.now().subtract(const Duration(hours: 3)),
        expiresAt: DateTime.now().add(const Duration(hours: 21)),
        reactions: Reactions(
          like: 40,
          love: 15,
          fire: 9,
        ),
        hasReacted: "love",
      ),
      Story(
        id: "story_2",
        mediaUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b",
        text: "Behind the scenes of today's shoot 📸",
        createdAt: DateTime.now().subtract(const Duration(hours: 1)),
        expiresAt: DateTime.now().add(const Duration(hours: 23)),
        reactions: Reactions(
          like: 18,
          love: 7,
          fire: 5,
        ),
        hasReacted: null,
      ),
    ],
  ),
  OwnerStory(
    store: Store(
      id: "store_2",
      name: "Urban Thread",
      location: "London, UK",
      logoUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8",
      mainImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d",
      averageRating: 4,
      owner: Owner(
        id: "owner_2",
        firstName: "Oliver",
        lastName: "Smith",
      ),
    ),
    stories: [
      Story(
        id: "story_3",
        mediaUrl: "https://vz-668bef04-68b.b-cdn.net/a8a51946-40ad-44a5-a7c1-5b33ce70eaf9/play_360p.mp4",
        thumbnailUrl: "https://picsum.photos/id/1011/800/1200",
        text: "Streetwear drop tonight 🔥",
        createdAt: DateTime.now().subtract(const Duration(hours: 4)),
        expiresAt: DateTime.now().add(const Duration(hours: 20)),
        reactions: Reactions(
          like: 60,
          love: 12,
          fire: 40,
        ),
        hasReacted: "fire",
      ),
    ],
  ),
];

final storesInfo = [
  Store(
    id: "store_1",
    name: "Velvet Vogue",
    location: "Milan, Italy",
    logoUrl: "https://images.unsplash.com/photo-1521335629791-ce4aec67dd53",
    mainImage: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
    averageRating: 4,
description: "Velvet Vogue is a premium fashion boutique offering modern streetwear and elegant outfits designed for confident individuals.",
    owner: Owner(
      id: "owner_1",
      firstName: "Sophia",
      lastName: "Rossi",
    ),
  ),
  Store(
    id: "store_2",
    name: "Urban Thread",
    location: "London, UK",
    logoUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8",
    mainImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d",
    averageRating: 4,
    description: "Adidas is a premium fashion boutique offering modern streetwear and elegant outfits designed for confident individuals.",
    owner: Owner(
      id: "owner_2",
      firstName: "Oliver",
      lastName: "Smith",
    ),
  ),
  Store(
    id: "store_3",
    name: "Nordic Style",
    location: "Stockholm, Sweden",
    latitude: "59.3293",
    longitude: "18.0686",
    logoUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b",
    mainImage: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    description: "Clean Scandinavian fashion aesthetics.",
    workingHours: "10:00 - 20:00",
    type: "Minimal Fashion",
    averageRating: 5,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    owner: Owner(
      id: "owner_3",
      firstName: "Emma",
      lastName: "Lindberg",
    ),
  ),
  Store(
    id: "store_4",
    name: "Urban Thread",
    location: "London, UK",
    latitude: "51.5072",
    longitude: "-0.1276",
    logoUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8",
    mainImage: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d",
    description: "Premium streetwear and casual fashion.",
    workingHours: "09:00 - 22:00",
    type: "Streetwear",
    averageRating: 4,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    owner: Owner(
      id: "owner_2",
      firstName: "Oliver",
      lastName: "Smith",
    ),
  ),
];